services:
  - type: web
    name: autostripe
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn autostripe:app -k quart.worker --bind 0.0.0.0:$PORT
    autoDeploy: true
